import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";

// Self-contained music player. Give it a station id; it loads
// public/music/<station>/manifest.json (generated by scripts/gen_manifests.mjs),
// shuffles the tracks, and plays them with prev/play-pause/next + volume. A
// track entry may be a bare filename (served from /music/<station>/) or an
// absolute URL (e.g. a CDN/Blob delivery). Matches the repo's inline-style
// convention; drop it anywhere in the React tree.

interface Manifest { tracks?: string[] }

const isAbsolute = (f: string) => /^(https?:)?\/\//.test(f);
const trackUrl = (station: string, f: string) => (isAbsolute(f) ? f : `/music/${station}/${f}`);

function shuffle<T>(arr: T[]): T[] {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function MusicPlayer({
  station,
  autoStart = false,
  initialVolume = 0.6,
}: {
  station: string;
  autoStart?: boolean;
  initialVolume?: number;
}) {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const [tracks, setTracks] = useState<string[]>([]);
  const [index, setIndex] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [volume, setVolume] = useState(initialVolume);
  const [error, setError] = useState<string | null>(null);

  // (re)load the manifest whenever the active station changes
  useEffect(() => {
    let alive = true;
    setError(null);
    setTracks([]);
    setIndex(0);
    fetch(`/music/${station}/manifest.json`, { cache: "no-cache" })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`manifest HTTP ${r.status}`))))
      .then((m: Manifest) => {
        if (!alive) return;
        const list = (m.tracks ?? []).map((f) => trackUrl(station, f));
        if (!list.length) { setError("No tracks for this station yet."); return; }
        setTracks(shuffle(list));
        if (autoStart) setPlaying(true);
      })
      .catch((e) => { if (alive) setError(String(e.message ?? e)); });
    return () => { alive = false; };
  }, [station, autoStart]);

  // load the current track + honor play state when the track/playlist changes
  useEffect(() => {
    const a = audioRef.current;
    if (!a || !tracks.length) return;
    a.src = tracks[index];
    if (playing) a.play().catch(() => setPlaying(false)); // autoplay may be blocked
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tracks, index]);

  // play/pause toggle (button click is a user gesture → playback is allowed)
  useEffect(() => {
    const a = audioRef.current;
    if (!a || !tracks.length) return;
    if (playing) a.play().catch(() => setPlaying(false));
    else a.pause();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [playing]);

  // keep element volume in sync
  useEffect(() => { if (audioRef.current) audioRef.current.volume = volume; }, [volume]);

  const next = () => setIndex((i) => (tracks.length ? (i + 1) % tracks.length : 0));
  const prev = () => setIndex((i) => (tracks.length ? (i - 1 + tracks.length) % tracks.length : 0));

  const nowPlaying = useMemo(() => {
    const u = tracks[index];
    if (!u) return "—";
    return decodeURIComponent(u.split("/").pop() || u).replace(/\.(mp3|m4a|aac|ogg|wav)$/i, "");
  }, [tracks, index]);

  return (
    <div style={wrap}>
      <audio ref={audioRef} onEnded={next} preload="auto" />
      <div style={{ ...row, justifyContent: "space-between", marginBottom: 6 }}>
        <span style={{ fontWeight: 700, letterSpacing: 1, color: "#ff7ad9" }}>{station.toUpperCase()}</span>
        <span style={{ opacity: 0.65, fontSize: 12 }}>{tracks.length ? `${index + 1}/${tracks.length}` : "—"}</span>
      </div>
      <div style={title} title={nowPlaying}>{error ?? nowPlaying}</div>
      <div style={row}>
        <button style={btn} onClick={prev} disabled={!tracks.length} aria-label="Previous">⏮</button>
        <button style={{ ...btn, width: 54 }} onClick={() => setPlaying((p) => !p)} disabled={!tracks.length} aria-label="Play or pause">{playing ? "⏸" : "▶"}</button>
        <button style={btn} onClick={next} disabled={!tracks.length} aria-label="Next">⏭</button>
        <input
          type="range" min={0} max={1} step={0.01} value={volume}
          onChange={(e) => setVolume(parseFloat(e.target.value))}
          style={{ flex: 1, accentColor: "#ff7ad9" }} aria-label="Volume"
        />
      </div>
    </div>
  );
}

const wrap: CSSProperties = {
  width: 280, padding: "12px 14px", borderRadius: 12,
  background: "rgba(12,15,26,.9)", border: "1px solid #3a2a5e", color: "#e7e0ff",
  fontFamily: "'Courier New', monospace",
};
const row: CSSProperties = { display: "flex", alignItems: "center", gap: 8 };
const title: CSSProperties = {
  fontSize: 13, margin: "0 0 10px", height: 18, lineHeight: "18px",
  overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", opacity: 0.9,
};
const btn: CSSProperties = {
  cursor: "pointer", width: 40, height: 34, borderRadius: 8, fontSize: 15,
  border: "1px solid #3a2a5e", background: "rgba(40,30,70,.9)", color: "#e7e0ff",
};
